language: node_js

node_js:
  - '6'
  - '7'
  - '8'

sudo: false

matrix:
  fast_finish: true

branches:
  only:
  - master

install:
  - yarn

script:
  - yarn run build

cache:
  directories:
    - node_modules

git:
  depth: 1
